# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-24 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FCResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrcIP', models.CharField(max_length=50, verbose_name='\u6e90IP')),
                ('SrcPort', models.IntegerField(blank=True, null=True, verbose_name='\u6e90\u7aef\u53e3')),
                ('SrcLocation', models.CharField(blank=True, max_length=100, verbose_name='\u653b\u51fb\u6765\u6e90\u5730')),
                ('DestIP', models.CharField(blank=True, max_length=50, verbose_name='\u76ee\u7684IP')),
                ('DescPort', models.IntegerField(blank=True, null=True, verbose_name='\u76ee\u7684\u7aef\u53e3')),
                ('DestLocation', models.CharField(blank=True, max_length=100, verbose_name='\u653b\u51fb\u76ee\u7684\u5730')),
                ('AttTime', models.DateTimeField(blank=True, null=True, verbose_name='\u653b\u51fb\u65f6\u95f4')),
                ('FileInAttPackNum', models.IntegerField(blank=True, null=True, verbose_name='\u6587\u4ef6\u5305\u542b\u653b\u51fb\u6d41\u91cf\u6570\u636e\u5305\u4e2a\u6570')),
                ('FileInAttByte', models.IntegerField(blank=True, null=True, verbose_name='\u6587\u4ef6\u5305\u542b\u653b\u51fb\u6d41\u91cf\u5b57\u8282\u6570')),
                ('FileInValidAtt', models.BooleanField(verbose_name='\u6587\u4ef6\u5305\u542b\u6709\u6548\u653b\u51fb\u6807\u8bc6')),
                ('FileInAttType', models.IntegerField(blank=True, null=True, verbose_name='\u6587\u4ef6\u5305\u542b\u653b\u51fb\u7c7b\u578b')),
                ('FileInAttLevel', models.IntegerField(blank=True, null=True, verbose_name='\u6587\u4ef6\u5305\u542b\u653b\u51fb\u98ce\u9669\u7b49\u7ea7')),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=100, verbose_name='url')),
                ('NetProType', models.CharField(blank=True, max_length=30, verbose_name='\u7f51\u7edc\u534f\u8bae\u7c7b\u578b')),
                ('MesHeader', models.CharField(max_length=200, verbose_name='\u62a5\u6587\u5934')),
                ('MesBody', models.CharField(blank=True, max_length=500, verbose_name='\u62a5\u6587\u5185\u5bb9')),
                ('ResponseCode', models.IntegerField(blank=True, null=True, verbose_name='\u54cd\u5e94\u4ee3\u7801')),
                ('ResponseBody', models.CharField(blank=True, max_length=500, verbose_name='\u54cd\u5e94\u6b63\u6587')),
                ('SrcIP', models.CharField(max_length=50, verbose_name='\u6e90IP')),
                ('SrcPort', models.IntegerField(blank=True, null=True, verbose_name='\u6e90\u7aef\u53e3')),
                ('SrcWlan', models.CharField(blank=True, max_length=100, verbose_name='\u6e90\u57ce\u57df\u7f51')),
                ('DescIP', models.CharField(blank=True, max_length=50, verbose_name='\u76ee\u7684IP')),
                ('DescPort', models.IntegerField(null=True, verbose_name='\u76ee\u7684\u7aef\u53e3')),
                ('DescWlan', models.CharField(blank=True, max_length=100, verbose_name='\u76ee\u7684\u5730\u57ce\u57df\u7f51')),
                ('DPI_Byte', models.IntegerField(blank=True, null=True, verbose_name='DPI\u6d41\u91cf\u5b57\u8282\u6570')),
                ('DPI_Packet', models.IntegerField(blank=True, null=True, verbose_name='DPI\u6d41\u91cf\u6570\u636e\u5305\u4e2a\u6570')),
                ('UTC_Time', models.DateTimeField(blank=True, null=True, verbose_name='UTC\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='RCResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrcIP', models.CharField(max_length=50, verbose_name='\u6e90IP')),
                ('SrcPort', models.IntegerField(blank=True, null=True, verbose_name='\u6e90\u7aef\u53e3')),
                ('SrcLocation', models.CharField(blank=True, max_length=100, verbose_name='\u653b\u51fb\u6765\u6e90\u5730')),
                ('DestIP', models.CharField(blank=True, max_length=50, verbose_name='\u76ee\u7684IP')),
                ('DescPort', models.IntegerField(blank=True, null=True, verbose_name='\u76ee\u7684\u7aef\u53e3')),
                ('DestLocation', models.CharField(blank=True, max_length=100, verbose_name='\u653b\u51fb\u76ee\u7684\u5730')),
                ('AttTime', models.DateTimeField(blank=True, null=True, verbose_name='\u653b\u51fb\u65f6\u95f4')),
                ('RCE_AttPackNum', models.IntegerField(blank=True, null=True, verbose_name='\u8fdc\u7a0b\u547d\u4ee4\u6267\u884c\u653b\u51fb\u6d41\u91cf\u6570\u636e\u5305\u4e2a\u6570')),
                ('RCE_AttByte', models.IntegerField(blank=True, null=True, verbose_name='\u8fdc\u7a0b\u547d\u4ee4\u6267\u884c\u653b\u51fb\u6d41\u91cf\u5b57\u8282\u6570')),
                ('RCE_ValidAtt', models.BooleanField(verbose_name='\u8fdc\u7a0b\u547d\u4ee4\u6267\u884c\u6709\u6548\u653b\u51fb\u6807\u8bc6')),
                ('RCE_AttType', models.IntegerField(blank=True, null=True, verbose_name='\u8fdc\u7a0b\u547d\u4ee4\u6267\u884c\u653b\u51fb\u7c7b\u578b')),
                ('RCE_AttLevel', models.IntegerField(blank=True, null=True, verbose_name='\u8fdc\u7a0b\u547d\u4ee4\u6267\u884c\u653b\u51fb\u98ce\u9669\u7b49\u7ea7')),
                ('Flow_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.Flow', verbose_name='\u5bf9\u5e94DPI\u6d41\u91cfID')),
            ],
        ),
        migrations.CreateModel(
            name='SQLInjecResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrcIP', models.CharField(max_length=50, verbose_name='\u6e90IP')),
                ('SrcPort', models.IntegerField(blank=True, null=True, verbose_name='\u6e90\u7aef\u53e3')),
                ('SrcLocation', models.CharField(blank=True, max_length=100, verbose_name='\u653b\u51fb\u6765\u6e90\u5730')),
                ('DestIP', models.CharField(blank=True, max_length=50, verbose_name='\u76ee\u7684IP')),
                ('DescPort', models.IntegerField(blank=True, null=True, verbose_name='\u76ee\u7684\u7aef\u53e3')),
                ('DestLocation', models.CharField(blank=True, max_length=100, verbose_name='\u653b\u51fb\u76ee\u7684\u5730')),
                ('AttTime', models.DateTimeField(blank=True, null=True, verbose_name='\u653b\u51fb\u65f6\u95f4')),
                ('SqlInjAttPackNum', models.IntegerField(blank=True, null=True, verbose_name='SQL\u6ce8\u5165\u653b\u51fb\u6d41\u91cf\u6570\u636e\u5305\u4e2a\u6570')),
                ('SqlInjAttByte', models.IntegerField(blank=True, null=True, verbose_name='SQL\u6ce8\u5165\u653b\u51fb\u6d41\u91cf\u5b57\u8282\u6570')),
                ('SqlInjValidAtt', models.BooleanField(verbose_name='SQL\u6ce8\u5165\u6709\u6548\u653b\u51fb\u6807\u8bc6')),
                ('SqlInjAttType', models.IntegerField(blank=True, null=True, verbose_name='SQL\u6ce8\u5165\u653b\u51fb\u7c7b\u578b')),
                ('SqlInjAttLevel', models.IntegerField(blank=True, null=True, verbose_name='SQL\u6ce8\u5165\u653b\u51fb\u98ce\u9669\u7b49\u7ea7')),
                ('Flow_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.Flow', verbose_name='\u5bf9\u5e94DPI\u6d41\u91cfID')),
            ],
        ),
        migrations.CreateModel(
            name='WebBDResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrcIP', models.CharField(max_length=50, verbose_name='\u6e90IP')),
                ('SrcPort', models.IntegerField(blank=True, null=True, verbose_name='\u6e90\u7aef\u53e3')),
                ('SrcLocation', models.CharField(blank=True, max_length=100, verbose_name='\u653b\u51fb\u6765\u6e90\u5730')),
                ('DestIP', models.CharField(blank=True, max_length=50, verbose_name='\u76ee\u7684IP')),
                ('DescPort', models.IntegerField(blank=True, null=True, verbose_name='\u76ee\u7684\u7aef\u53e3')),
                ('DestLocation', models.CharField(blank=True, max_length=100, verbose_name='\u653b\u51fb\u76ee\u7684\u5730')),
                ('AttTime', models.DateTimeField(blank=True, null=True, verbose_name='\u653b\u51fb\u65f6\u95f4')),
                ('WebShellAttPackNum', models.IntegerField(blank=True, null=True, verbose_name='Web\u540e\u95e8\u653b\u51fb\u6d41\u91cf\u6570\u636e\u5305\u4e2a\u6570')),
                ('WebShellAttByte', models.IntegerField(blank=True, null=True, verbose_name='Web\u540e\u95e8\u653b\u51fb\u6d41\u91cf\u5b57\u8282\u6570')),
                ('WebShellValidAtt', models.BooleanField(verbose_name='Web\u540e\u95e8\u6709\u6548\u653b\u51fb\u6807\u8bc6')),
                ('WebShellAttType', models.IntegerField(blank=True, null=True, verbose_name='Web\u540e\u95e8\u653b\u51fb\u7c7b\u578b')),
                ('WebShellAttLevel', models.IntegerField(blank=True, null=True, verbose_name='Web\u540e\u95e8\u653b\u51fb\u98ce\u9669\u7b49\u7ea7')),
                ('Flow_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.Flow', verbose_name='\u5bf9\u5e94DPI\u6d41\u91cfID')),
            ],
        ),
        migrations.CreateModel(
            name='XSSResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrcIP', models.CharField(max_length=50, verbose_name='\u6e90IP')),
                ('SrcPort', models.IntegerField(blank=True, null=True, verbose_name='\u6e90\u7aef\u53e3')),
                ('SrcLocation', models.CharField(blank=True, max_length=100, verbose_name='\u653b\u51fb\u6765\u6e90\u5730')),
                ('DestIP', models.CharField(blank=True, max_length=50, verbose_name='\u76ee\u7684IP')),
                ('DescPort', models.IntegerField(blank=True, null=True, verbose_name='\u76ee\u7684\u7aef\u53e3')),
                ('DestLocation', models.CharField(blank=True, max_length=100, verbose_name='\u653b\u51fb\u76ee\u7684\u5730')),
                ('AttTime', models.DateTimeField(blank=True, null=True, verbose_name='\u653b\u51fb\u65f6\u95f4')),
                ('XssAttPackNum', models.IntegerField(blank=True, null=True, verbose_name='XSS\u653b\u51fb\u6d41\u91cf\u6570\u636e\u5305\u4e2a\u6570')),
                ('XssAttByte', models.IntegerField(blank=True, null=True, verbose_name='Xss\u653b\u51fb\u6d41\u91cf\u5b57\u8282\u6570')),
                ('XssValidAtt', models.BooleanField(verbose_name='Xss\u6709\u6548\u653b\u51fb\u6807\u8bc6')),
                ('XssAttType', models.IntegerField(blank=True, null=True, verbose_name='Xss\u653b\u51fb\u7c7b\u578b')),
                ('XssAttLevel', models.IntegerField(blank=True, null=True, verbose_name='Xss\u653b\u51fb\u98ce\u9669\u7b49\u7ea7')),
                ('Flow_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.Flow', verbose_name='\u5bf9\u5e94DPI\u6d41\u91cfID')),
            ],
        ),
        migrations.AddField(
            model_name='fcresult',
            name='Flow_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.Flow', verbose_name='\u5bf9\u5e94DPI\u6d41\u91cfID'),
        ),
    ]
