# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-10 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='AttType',
            field=models.IntegerField(null=True, verbose_name='\u653b\u51fb\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='flow',
            name='DescGeoPos',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u76ee\u7684\u5730\u7406\u4f4d\u7f6e'),
        ),
        migrations.AddField(
            model_name='flow',
            name='SrcGeoPost',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u6e90\u5730\u7406\u4f4d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='DPI_Byte',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='DPI\u6d41\u91cf\u5b57\u8282\u6570'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flow',
            name='DPI_Packet',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='DPI\u6d41\u91cf\u6570\u636e\u5305\u4e2a\u6570'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flow',
            name='DescPort',
            field=models.CharField(default='', max_length=50, verbose_name='\u76ee\u7684\u7aef\u53e3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flow',
            name='MesBody',
            field=models.CharField(blank=True, max_length=5000, verbose_name='\u62a5\u6587\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='MesHeader',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u62a5\u6587\u5934'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='ResponseBody',
            field=models.CharField(blank=True, max_length=5000, verbose_name='\u54cd\u5e94\u6b63\u6587'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='ResponseCode',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='\u54cd\u5e94\u4ee3\u7801'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flow',
            name='SrcPort',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='\u6e90\u7aef\u53e3'),
            preserve_default=False,
        ),
    ]
