# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-14 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20151210_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcresult',
            name='DestIP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u76ee\u7684IP'),
        ),
        migrations.AlterField(
            model_name='fcresult',
            name='DestLocation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u653b\u51fb\u76ee\u7684\u5730'),
        ),
        migrations.AlterField(
            model_name='fcresult',
            name='FileInValidAtt',
            field=models.BooleanField(default=0, verbose_name='\u6587\u4ef6\u5305\u542b\u6709\u6548\u653b\u51fb\u6807\u8bc6'),
        ),
        migrations.AlterField(
            model_name='fcresult',
            name='SrcIP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6e90IP'),
        ),
        migrations.AlterField(
            model_name='fcresult',
            name='SrcLocation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u653b\u51fb\u6765\u6e90\u5730'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='AttType',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u653b\u51fb\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='DPI_Byte',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DPI\u6d41\u91cf\u5b57\u8282\u6570'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='DPI_Packet',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DPI\u6d41\u91cf\u6570\u636e\u5305\u4e2a\u6570'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='DescGeoPos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u76ee\u7684\u5730\u7406\u4f4d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='DescIP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u76ee\u7684IP'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='DescPort',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u76ee\u7684\u7aef\u53e3'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='DescWlan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u76ee\u7684\u5730\u57ce\u57df\u7f51'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='MesBody',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u62a5\u6587\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='MesHeader',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u62a5\u6587\u5934'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='NetProType',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7f51\u7edc\u534f\u8bae\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='ResponseBody',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u54cd\u5e94\u6b63\u6587'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='ResponseCode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u54cd\u5e94\u4ee3\u7801'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='SrcGeoPost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6e90\u5730\u7406\u4f4d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='SrcIP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6e90IP'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='SrcPort',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6e90\u7aef\u53e3'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='SrcWlan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6e90\u57ce\u57df\u7f51'),
        ),
        migrations.AlterField(
            model_name='rcresult',
            name='DestIP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u76ee\u7684IP'),
        ),
        migrations.AlterField(
            model_name='rcresult',
            name='DestLocation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u653b\u51fb\u76ee\u7684\u5730'),
        ),
        migrations.AlterField(
            model_name='rcresult',
            name='RCE_ValidAtt',
            field=models.BooleanField(default=0, verbose_name='\u8fdc\u7a0b\u547d\u4ee4\u6267\u884c\u6709\u6548\u653b\u51fb\u6807\u8bc6'),
        ),
        migrations.AlterField(
            model_name='rcresult',
            name='SrcIP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6e90IP'),
        ),
        migrations.AlterField(
            model_name='rcresult',
            name='SrcLocation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u653b\u51fb\u6765\u6e90\u5730'),
        ),
        migrations.AlterField(
            model_name='sqlinjecresult',
            name='DestIP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u76ee\u7684IP'),
        ),
        migrations.AlterField(
            model_name='sqlinjecresult',
            name='DestLocation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u653b\u51fb\u76ee\u7684\u5730'),
        ),
        migrations.AlterField(
            model_name='sqlinjecresult',
            name='SqlInjValidAtt',
            field=models.BooleanField(default=0, verbose_name='SQL\u6ce8\u5165\u6709\u6548\u653b\u51fb\u6807\u8bc6'),
        ),
        migrations.AlterField(
            model_name='sqlinjecresult',
            name='SrcIP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6e90IP'),
        ),
        migrations.AlterField(
            model_name='sqlinjecresult',
            name='SrcLocation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u653b\u51fb\u6765\u6e90\u5730'),
        ),
        migrations.AlterField(
            model_name='webbdresult',
            name='DestIP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u76ee\u7684IP'),
        ),
        migrations.AlterField(
            model_name='webbdresult',
            name='DestLocation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u653b\u51fb\u76ee\u7684\u5730'),
        ),
        migrations.AlterField(
            model_name='webbdresult',
            name='SrcIP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6e90IP'),
        ),
        migrations.AlterField(
            model_name='webbdresult',
            name='SrcLocation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u653b\u51fb\u6765\u6e90\u5730'),
        ),
        migrations.AlterField(
            model_name='webbdresult',
            name='WebShellValidAtt',
            field=models.BooleanField(default=0, verbose_name='Web\u540e\u95e8\u6709\u6548\u653b\u51fb\u6807\u8bc6'),
        ),
        migrations.AlterField(
            model_name='xssresult',
            name='DestIP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u76ee\u7684IP'),
        ),
        migrations.AlterField(
            model_name='xssresult',
            name='DestLocation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u653b\u51fb\u76ee\u7684\u5730'),
        ),
        migrations.AlterField(
            model_name='xssresult',
            name='SrcIP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6e90IP'),
        ),
        migrations.AlterField(
            model_name='xssresult',
            name='SrcLocation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u653b\u51fb\u6765\u6e90\u5730'),
        ),
        migrations.AlterField(
            model_name='xssresult',
            name='XssValidAtt',
            field=models.BooleanField(default=0, verbose_name='Xss\u6709\u6548\u653b\u51fb\u6807\u8bc6'),
        ),
    ]
